### ISSUE TITLE
Turn a scene on / off 

### ISSUE THREAD

**Issue by nbouliol** [yuqio/huelib-rs#7]
Hi, 

How can I turn a scene on / off ?

I tried

```rust
use huelib::resource::scene::LightStateModifier;
use huelib::{bridge, Bridge};

fn main() {
  let bridge_ip = bridge::discover().unwrap().pop().unwrap();

  let user = bridge::User {
    name: String::from("username"),
    clientkey: None,
  };

  let bridge = Bridge::new(bridge_ip, &user.name);

  let m: LightStateModifier = huelib::resource::Modifier::new();
  m.on(true);
  bridge.set_scene("scene_id", m);
}
``` 

But `bridge::set_scene` does not accept a `LightStateModifier` :
```
error[E0308]: mismatched types
  --> src/main.rs:16:32
   |
16 |   bridge.set_scene("scene_id", m);
   |                                ^ expected `&huelib::resource::scene::Modifier`, found struct `huelib::resource::scene::LightStateModifier`
```

**Comment by yuqio** [comment]
The parameter type of the function `set_scene` is `scene::Modifier` and not `scene::LightStateModifier`. To change the state of a light you first have to create a `scene::Modifier` and then call the function `light_state` with the `LightStateModifier` and a light ID as parameter.

For example:
```rust
use huelib::resource::{scene, Modifier};

let m = scene::Modifier::new().light_state("light_id", scene::LightStateModifier::new().on(true));
```
Note that the trait `huelib::resource::Modifier` is brought into scope here because the function `new` of `scene::Modifier` and `scene::LightStateModifier` are part of that trait.

You also have to pass the modifier as a reference to the `set_scene` function with `&`:
```rust
bridge.set_scene("scene_id", &m);
```

**Comment by nbouliol** [comment]
Thanks for your response!

By doing this, the lights of my scene stay off

```rust
if let Some(lights) = &selected_scene.lights {
      let mut m = scene::Modifier::new();
      for light in lights {
        m = m.light_state(light, scene::LightStateModifier::new().on(true));
      }
      let res = bridge.set_scene(&selected_scene.id, &m);
      dbg!(res);
    }
```

A scene is a preset of color, temperature, and brightness for a group so why can't I just do something like 

```rust
let m = scene::Modifier::new().on();
bridge.set_scene("scene_id", &m);
```
